#!/bin/bash

# Проверяем, что переданы оба параметра
if [ $# -ne 2 ]; then
    echo "Правильный запуск: ./script.sh <файл> <слово>"
    exit 1
fi

#0 аргумент - сам файл
file=$1
word=$2

# Ищем слово 
grep "$word" "$file"
